name: Build Status

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test bash Syntax
      run: if find . -name "*.sh" -exec /bin/bash -n {} \; | grep "syntax error"; then exit 1; fi



